"""Per-region map from museum `place` string → country slug.

Used to route V&A results (whose `_primaryPlace` is often a city like "Bukhara"
or a region like "Central Asia") into the right country tree, and to reject
records whose place points somewhere outside the target region entirely
(e.g. "Cairo" showing up in a muqarnas search).

Each region has:
  place_to_country: {place_string: country_or_"_regional"}
  reject_places:    {places we know are OUTSIDE this region}

Anything in `place_to_country` gets routed; anything explicitly listed in
`reject_places` or unlisted gets skipped.

Signature-tradition escape hatch: some object types are so tightly bound to a
single culture that we accept them even with a vague/empty place — see
`signature_traditions` per region.
"""
from __future__ import annotations

CENTRAL_ASIA = {
    "place_to_country": {
        "uzbekistan": "Uzbekistan",
        "bukhara": "Uzbekistan",
        "samarkand": "Uzbekistan",
        "samarqand": "Uzbekistan",
        "khiva": "Uzbekistan",
        "tashkent": "Uzbekistan",
        "fergana": "Uzbekistan",
        "ferghana": "Uzbekistan",
        "namangan": "Uzbekistan",
        "kokand": "Uzbekistan",
        "shakhrisabz": "Uzbekistan",
        "termez": "Uzbekistan",
        "turkmenistan": "Turkmenistan",
        "merv": "Turkmenistan",
        "ashgabat": "Turkmenistan",
        "kazakhstan": "Kazakhstan",
        "almaty": "Kazakhstan",
        "kyrgyzstan": "Kyrgyzstan",
        "bishkek": "Kyrgyzstan",
        "tajikistan": "Tajikistan",
        "dushanbe": "Tajikistan",
        "pamir": "Tajikistan",
        "khujand": "Tajikistan",
        "afghanistan": "Afghanistan",
        "kabul": "Afghanistan",
        "herat": "Afghanistan",
        "balkh": "Afghanistan",
        "mazar-i-sharif": "Afghanistan",
        "mazar-e-sharif": "Afghanistan",
        "kandahar": "Afghanistan",
        "hotan": "China (Xinjiang)",
        "khotan": "China (Xinjiang)",
        "kashgar": "China (Xinjiang)",
        "turfan": "China (Xinjiang)",
        "xinjiang": "China (Xinjiang)",
        "chinese turkestan": "China (Xinjiang)",
        "east turkestan": "China (Xinjiang)",
        "central asia": "_regional",
        "turkestan": "_regional",
        "silk road": "_regional",
        "transoxiana": "_regional",
        "bactria": "_regional",
        "sogdiana": "_regional",
    },
    "reject_places": {
        # Known outside-the-region tokens we've seen in false-positive results
        "cairo", "damascus", "constantinople", "istanbul", "turkey",
        "iran", "persia", "iranian",
        "india", "gujarat", "kashmir",
        "egypt", "syria",
        "china", "tibet", "central tibet",
        "japan", "korea",
        "europe", "italy", "france", "netherlands", "germany", "spain",
        "russia", "moscow", "ukraine",
    },
    "signature_traditions": {
        # objectType-substring -> default country when place is empty/regional
        "suzani": "Uzbekistan",
        "ikat length": "Uzbekistan",  # majority is Uzbek/Uyghur; will refine
        "khan-atlas": "Uzbekistan",
        "adras": "Uzbekistan",
        "chapan": "_regional",
        "kurta": "_regional",
        "doppa": "China (Xinjiang)",
        "kalpak": "Kyrgyzstan",
        "shyrdak": "Kyrgyzstan",
        "yurt band": "_regional",
    },
}


SOUTHEAST_ASIA = {
    "place_to_country": {
        "indonesia": "Indonesia",
        "dutch east indies": "Indonesia",
        "java": "Indonesia",
        "west java": "Indonesia",
        "central java": "Indonesia",
        "east java": "Indonesia",
        "yogyakarta": "Indonesia",
        "jogjakarta": "Indonesia",
        "solo": "Indonesia",
        "surakarta": "Indonesia",
        "cirebon": "Indonesia",
        "pekalongan": "Indonesia",
        "sumatra": "Indonesia",
        "west sumatra": "Indonesia",
        "north sumatra": "Indonesia",
        "palembang": "Indonesia",
        "medan": "Indonesia",
        "aceh": "Indonesia",
        "batak": "Indonesia",
        "bali": "Indonesia",
        "denpasar": "Indonesia",
        "kalimantan": "Indonesia",
        "borneo": "_regional",  # spans Indonesia + Malaysia + Brunei
        "sarawak": "Malaysia",
        "sabah": "Malaysia",
        "sulawesi": "Indonesia",
        "celebes": "Indonesia",
        "toraja": "Indonesia",
        "flores": "Indonesia",
        "sumba": "Indonesia",
        "timor": "Indonesia",
        "maluku": "Indonesia",
        "papua": "Indonesia",
        "new guinea": "_regional",
        "malaysia": "Malaysia",
        "malay peninsula": "Malaysia",
        "kuala lumpur": "Malaysia",
        "penang": "Malaysia",
        "melaka": "Malaysia",
        "malacca": "Malaysia",
        "kelantan": "Malaysia",
        "terengganu": "Malaysia",
        "brunei": "Malaysia",
        "singapore": "Malaysia",  # historically part of Malay peninsula workshop tradition
        "thailand": "Thailand",
        "siam": "Thailand",
        "siamese": "Thailand",
        "bangkok": "Thailand",
        "chiang mai": "Thailand",
        "isan": "Thailand",
        "vietnam": "Vietnam",
        "annam": "Vietnam",
        "tonkin": "Vietnam",
        "champa": "Vietnam",
        "hanoi": "Vietnam",
        "saigon": "Vietnam",
        "ho chi minh": "Vietnam",
        "hue": "Vietnam",
        "cambodia": "Cambodia",
        "cambodian": "Cambodia",
        "khmer": "Cambodia",
        "phnom penh": "Cambodia",
        "siem reap": "Cambodia",
        "angkor": "Cambodia",
        "laos": "Laos",
        "lao": "Laos",
        "luang prabang": "Laos",
        "vientiane": "Laos",
        "myanmar": "Myanmar",
        "burma": "Myanmar",
        "burmese": "Myanmar",
        "yangon": "Myanmar",
        "rangoon": "Myanmar",
        "mandalay": "Myanmar",
        "shan": "Myanmar",
        "chin": "Myanmar",
        "philippines": "Philippines",
        "filipino": "Philippines",
        "manila": "Philippines",
        "mindanao": "Philippines",
        "sulu": "Philippines",
        "basilan": "Philippines",
        "cotabato": "Philippines",
        "luzon": "Philippines",
        "southeast asia": "_regional",
        "south-east asia": "_regional",
        "indochina": "_regional",
        "east indies": "_regional",
    },
    "reject_places": {
        "china", "japan", "korea", "india", "pakistan", "sri lanka", "bangladesh",
        "iran", "persia", "afghanistan", "uzbekistan",
        "europe", "italy", "france", "netherlands", "germany", "spain",
        "australia", "papua new guinea",
        "americas", "united states", "mexico",
        "central asia",
    },
    "signature_traditions": {
        "batik": "Indonesia",           # most batik in museum collections is Java/Sumatra
        "songket": "Indonesia",
        "gringsing": "Indonesia",
        "ulos": "Indonesia",
        "pua kumbu": "Malaysia",        # Iban, mostly Sarawak
        "mudmee": "Thailand",
        "hol": "Cambodia",
        "sinh": "Laos",
        "acheik": "Myanmar",
        "longyi": "Myanmar",
        "kalaga": "Myanmar",
        "t'nalak": "Philippines",
        "paj ntaub": "Vietnam",         # Hmong
        "sarong": "_regional",          # sarong spans the region
        "ikat": "_regional",            # SE Asian ikat is mostly Indonesian but not always
        "kain panjang": "Indonesia",
    },
}


MENA = {
    "place_to_country": {
        'iran': 'Iran',
        'persia': 'Iran',
        'persian': 'Iran',
        'tehran': 'Iran',
        'isfahan': 'Iran',
        'esfahan': 'Iran',
        'ispahan': 'Iran',
        'shiraz': 'Iran',
        'tabriz': 'Iran',
        'kashan': 'Iran',
        'kerman': 'Iran',
        'mashhad': 'Iran',
        'qom': 'Iran',
        'yazd': 'Iran',
        'hamadan': 'Iran',
        'nishapur': 'Iran',
        'neyshabur': 'Iran',
        'khorasan': 'Iran',
        'gilan': 'Iran',
        'mazandaran': 'Iran',
        'luristan': 'Iran',
        'lorestan': 'Iran',
        'azerbaijan (iran)': 'Iran',
        'iranian azerbaijan': 'Iran',
        'morocco': 'Morocco',
        'maroc': 'Morocco',
        'moroccan': 'Morocco',
        'marocain': 'Morocco',
        'fez': 'Morocco',
        'fes': 'Morocco',
        'fès': 'Morocco',
        'marrakesh': 'Morocco',
        'marrakech': 'Morocco',
        'rabat': 'Morocco',
        'meknes': 'Morocco',
        'meknès': 'Morocco',
        'tetouan': 'Morocco',
        'tétouan': 'Morocco',
        'chefchaouen': 'Morocco',
        'essaouira': 'Morocco',
        'casablanca': 'Morocco',
        'tangier': 'Morocco',
        'tanger': 'Morocco',
        'salé': 'Morocco',
        'sale': 'Morocco',
        'atlas mountains': 'Morocco',
        'haut atlas': 'Morocco',
        'moyen atlas': 'Morocco',
        'rif': 'Morocco',
        'sous': 'Morocco',
        'souss': 'Morocco',
        'tunisia': 'Tunisia',
        'tunisie': 'Tunisia',
        'tunisian': 'Tunisia',
        'tunisien': 'Tunisia',
        'tunis': 'Tunisia',
        'kairouan': 'Tunisia',
        'sfax': 'Tunisia',
        'sousse': 'Tunisia',
        'mahdia': 'Tunisia',
        'djerba': 'Tunisia',
        'jerba': 'Tunisia',
        'nabeul': 'Tunisia',
        'carthage': 'Tunisia',
        'egypt': 'Egypt',
        'egyptian': 'Egypt',
        'égypte': 'Egypt',
        'cairo': 'Egypt',
        'le caire': 'Egypt',
        'alexandria': 'Egypt',
        'alexandrie': 'Egypt',
        'fustat': 'Egypt',
        'giza': 'Egypt',
        'luxor': 'Egypt',
        'thebes': 'Egypt',
        'aswan': 'Egypt',
        'sinai': 'Egypt',
        'upper egypt': 'Egypt',
        'lower egypt': 'Egypt',
        'coptic egypt': 'Egypt',
        'mamluk egypt': 'Egypt',
        'turkey': 'Turkey',
        'türkiye': 'Turkey',
        'turkiye': 'Turkey',
        'turquie': 'Turkey',
        'turkish': 'Turkey',
        'anatolia': 'Turkey',
        'anatolian': 'Turkey',
        'asia minor': 'Turkey',
        'ottoman empire': 'Turkey',
        'ottoman': 'Turkey',
        'istanbul': 'Turkey',
        'constantinople': 'Turkey',
        'iznik': 'Turkey',
        'bursa': 'Turkey',
        'izmir': 'Turkey',
        'smyrna': 'Turkey',
        'konya': 'Turkey',
        'edirne': 'Turkey',
        'adrianople': 'Turkey',
        'kutahya': 'Turkey',
        'kütahya': 'Turkey',
        'cappadocia': 'Turkey',
        'hereke': 'Turkey',
        'usak': 'Turkey',
        'uşak': 'Turkey',
        'maghreb': '_regional',
        'maghrib': '_regional',
        'north africa': '_regional',
        'afrique du nord': '_regional',
        'berber': '_regional',
        'amazigh': '_regional',
        'islamic world': '_regional',
        'middle east': '_regional',
        'near east': '_regional',
    },
    "reject_places": {
        'afghanistan',
        'al-andalus',
        'algeria',
        'algérie',
        'andalusia',
        'arabia',
        'armenia',
        'azerbaijan',
        'bahrain',
        'bhutan',
        'bukhara',
        'burma',
        'cambodia',
        'caucasus',
        'chad',
        'china',
        'cyprus',
        'east africa',
        'eritrea',
        'ethiopia',
        'france',
        'georgia',
        'greece',
        'hejaz',
        'india',
        'indonesia',
        'iraq',
        'israel',
        'italy',
        'japan',
        'jordan',
        'kashmir',
        'kazakhstan',
        'korea',
        'kuwait',
        'kyrgyzstan',
        'lebanon',
        'libya',
        'malaysia',
        'mali',
        'mauritania',
        'mesopotamia',
        'mongolia',
        'myanmar',
        'nepal',
        'nigeria',
        'oman',
        'pakistan',
        'palestine',
        'philippines',
        'portugal',
        'qatar',
        'russia',
        'samarkand',
        'saudi arabia',
        'senegal',
        'somalia',
        'spain',
        'sri lanka',
        'sub-saharan africa',
        'sudan',
        'syria',
        'tajikistan',
        'tashkent',
        'thailand',
        'tibet',
        'turkmenistan',
        'uae',
        'uzbekistan',
        'vietnam',
        'west africa',
        'xinjiang',
        'yemen',
    },
    "signature_traditions": {
        'iznik': 'Turkey',
        'kutahya ware': 'Turkey',
        'hereke rug': 'Turkey',
        'hereke carpet': 'Turkey',
        'usak carpet': 'Turkey',
        'ushak carpet': 'Turkey',
        'ottoman tugra': 'Turkey',
        'tughra': 'Turkey',
        'cintamani': 'Turkey',
        'qashqai': 'Iran',
        'kashkai': 'Iran',
        'bakhtiari': 'Iran',
        'kilim shiraz': 'Iran',
        'safavid': 'Iran',
        'qajar': 'Iran',
        'lusterware kashan': 'Iran',
        'minai ware': 'Iran',
        "mina'i": 'Iran',
        'beni ourain': 'Morocco',
        'beni mguild': 'Morocco',
        'boucherouite': 'Morocco',
        'azemmour embroidery': 'Morocco',
        'fez embroidery': 'Morocco',
        'zellige': 'Morocco',
        'tadelakt': 'Morocco',
        'babouche': 'Morocco',
        'chemla': 'Tunisia',
        'kairouan carpet': 'Tunisia',
        'mergoum': 'Tunisia',
        'coptic textile': 'Egypt',
        'mamluk carpet': 'Egypt',
        'mamluk glass': 'Egypt',
        'fatimid': 'Egypt',
        'fustat textile': 'Egypt',
    },
}


SUB_SAHARAN_AFRICA = {
    "place_to_country": {
        'senegal': 'Senegal',
        'sénégal': 'Senegal',
        'wolof': 'Senegal',
        'fulani': 'Senegal',
        'peul': 'Senegal',
        'peulh': 'Senegal',
        'fulbe': 'Senegal',
        'dakar': 'Senegal',
        'saint-louis du sénégal': 'Senegal',
        'sine-saloum': 'Senegal',
        'casamance': 'Senegal',
        'nigeria': 'Nigeria',
        'yoruba': 'Nigeria',
        'yorouba': 'Nigeria',
        'igbo': 'Nigeria',
        'ibo': 'Nigeria',
        'benin city': 'Nigeria',
        'kingdom of benin': 'Nigeria',
        'royaume du bénin': 'Nigeria',
        'ife': 'Nigeria',
        'ilé-ifè': 'Nigeria',
        'nok': 'Nigeria',
        'lagos': 'Nigeria',
        'nigéria': 'Nigeria',
        'biafra': 'Nigeria',
        'ghana': 'Ghana',
        'ashanti': 'Ghana',
        'asante': 'Ghana',
        'gold coast': 'Ghana',
        "côte-de-l'or": 'Ghana',
        'goldküste': 'Ghana',
        'kumasi': 'Ghana',
        'accra': 'Ghana',
        'fante': 'Ghana',
        'ethiopia': 'Ethiopia',
        'éthiopie': 'Ethiopia',
        'äthiopien': 'Ethiopia',
        'abyssinia': 'Ethiopia',
        'abyssinie': 'Ethiopia',
        'abessinien': 'Ethiopia',
        'amhara': 'Ethiopia',
        'oromo': 'Ethiopia',
        'galla': 'Ethiopia',
        'tigray': 'Ethiopia',
        'tigrinya': 'Ethiopia',
        'sidama': 'Ethiopia',
        'addis abeba': 'Ethiopia',
        'addis ababa': 'Ethiopia',
        'aksum': 'Ethiopia',
        'axum': 'Ethiopia',
        'gondar': 'Ethiopia',
        'lalibela': 'Ethiopia',
        'kenya': 'Kenya',
        'british east africa': 'Kenya',
        'afrique orientale britannique': 'Kenya',
        'kikuyu': 'Kenya',
        'gikuyu': 'Kenya',
        'maasai': 'Kenya',
        'masai': 'Kenya',
        'massaï': 'Kenya',
        'nairobi': 'Kenya',
        'tanzania': 'Tanzania',
        'tanzanie': 'Tanzania',
        'tansania': 'Tanzania',
        'tanganyika': 'Tanzania',
        'german east africa': 'Tanzania',
        'deutsch-ostafrika': 'Tanzania',
        'afrique orientale allemande': 'Tanzania',
        'zanzibar': 'Tanzania',
        'swahili': 'Tanzania',
        'souahéli': 'Tanzania',
        'makonde': 'Tanzania',
        'democratic republic of the congo': 'Democratic Republic of the Congo',
        'drc': 'Democratic Republic of the Congo',
        'dr congo': 'Democratic Republic of the Congo',
        'congo belge': 'Democratic Republic of the Congo',
        'belgian congo': 'Democratic Republic of the Congo',
        'belgisch kongo': 'Democratic Republic of the Congo',
        'belgisch-kongo': 'Democratic Republic of the Congo',
        'kongostaat': 'Democratic Republic of the Congo',
        'état indépendant du congo': 'Democratic Republic of the Congo',
        'congo free state': 'Democratic Republic of the Congo',
        'zaïre': 'Democratic Republic of the Congo',
        'zaire': 'Democratic Republic of the Congo',
        'kinshasa': 'Democratic Republic of the Congo',
        'léopoldville': 'Democratic Republic of the Congo',
        'leopoldville': 'Democratic Republic of the Congo',
        'katanga': 'Democratic Republic of the Congo',
        'kongo': 'Democratic Republic of the Congo',
        'bakongo': 'Democratic Republic of the Congo',
        'kuba': 'Democratic Republic of the Congo',
        'bakuba': 'Democratic Republic of the Congo',
        'chokwe': 'Democratic Republic of the Congo',
        'tchokwe': 'Democratic Republic of the Congo',
        'luba': 'Democratic Republic of the Congo',
        'songye': 'Democratic Republic of the Congo',
        'pende': 'Democratic Republic of the Congo',
        'gabon': 'Gabon',
        'fang': 'Gabon',
        'libreville': 'Gabon',
        'central african republic': 'Central African Republic',
        'république centrafricaine': 'Central African Republic',
        'zentralafrikanische republik': 'Central African Republic',
        'oubangui-chari': 'Central African Republic',
        'ubangi-shari': 'Central African Republic',
        'mbuti': 'Central African Republic',
        'bambuti': 'Central African Republic',
        'south africa': 'South Africa',
        'afrique du sud': 'South Africa',
        'südafrika': 'South Africa',
        'zuid-afrika': 'South Africa',
        'cape colony': 'South Africa',
        'colonie du cap': 'South Africa',
        'kapkolonie': 'South Africa',
        'transvaal': 'South Africa',
        'natal': 'South Africa',
        'zululand': 'South Africa',
        'zulu': 'South Africa',
        'zoulou': 'South Africa',
        'xhosa': 'South Africa',
        'ndebele': 'South Africa',
        'sotho': 'South Africa',
        'basutoland': 'South Africa',
        'namibia': 'Namibia',
        'namibie': 'Namibia',
        'südwestafrika': 'Namibia',
        'deutsch-südwestafrika': 'Namibia',
        'german south west africa': 'Namibia',
        'south west africa': 'Namibia',
        'sud-ouest africain': 'Namibia',
        'himba': 'Namibia',
        'ovambo': 'Namibia',
        'botswana': 'Botswana',
        'bechuanaland': 'Botswana',
        'betchouanaland': 'Botswana',
        'san': 'Botswana',
        'bushmen': 'Botswana',
        'bochiman': 'Botswana',
        'buschmänner': 'Botswana',
        'somalia': 'Somalia',
        'somalie': 'Somalia',
        'somali': 'Somalia',
        'somaliland': 'Somalia',
        'italian somaliland': 'Somalia',
        'somalia italiana': 'Somalia',
        'mogadishu': 'Somalia',
        'djibouti': 'Djibouti / Eritrea',
        'côte française des somalis': 'Djibouti / Eritrea',
        'french somaliland': 'Djibouti / Eritrea',
        'eritrea': 'Djibouti / Eritrea',
        'érythrée': 'Djibouti / Eritrea',
        'eritrea italiana': 'Djibouti / Eritrea',
        'afar': 'Djibouti / Eritrea',
        'asmara': 'Djibouti / Eritrea',
        'afrique-occidentale française': '_regional',
        'french west africa': '_regional',
        'aof': '_regional',
        'afrique-équatoriale française': '_regional',
        'french equatorial africa': '_regional',
        'aef': '_regional',
        'sub-saharan africa': '_regional',
        'afrique subsaharienne': '_regional',
        'west africa': '_regional',
        "afrique de l'ouest": '_regional',
        'east africa': '_regional',
        'afrique orientale': '_regional',
        'central africa': '_regional',
        'afrique centrale': '_regional',
        'southern africa': '_regional',
        'afrique australe': '_regional',
        'sahel': '_regional',
        'horn of africa': '_regional',
        "corne de l'afrique": '_regional',
        'great lakes region': '_regional',
    },
    "reject_places": {
        'afghanistan',
        'afrique du nord',
        'algeria',
        'algérie',
        'america',
        'americas',
        'arabia',
        'arctic',
        'australia',
        'austria',
        'bali',
        'borneo',
        'brazil',
        'britain',
        'burma',
        'cambodge',
        'cambodia',
        'caribbean',
        'central asia',
        'china',
        'chine',
        'cuba',
        'egypt',
        'england',
        'europe',
        'flanders',
        'france',
        'germany',
        'greece',
        'greenland',
        'haiti',
        'inde',
        'india',
        'indonesia',
        'indonésie',
        'iran',
        'iraq',
        'italy',
        'japan',
        'japon',
        'java',
        'kazakhstan',
        'korea',
        'laos',
        'levant',
        'libya',
        'libye',
        'madagascar',
        'maghreb',
        'malaysia',
        'maroc',
        'melanesia',
        'mena',
        'mexico',
        'micronesia',
        'middle east',
        'mongolia',
        'morocco',
        'myanmar',
        'nepal',
        'netherlands',
        'new zealand',
        'north africa',
        'north america',
        'oman',
        'ottoman empire',
        'pakistan',
        'papouasie',
        'papua new guinea',
        'perse',
        'persia',
        'peru',
        'philippines',
        'polynesia',
        'portugal',
        'russia',
        'saudi arabia',
        'scotland',
        'siberia',
        'soudan',
        'south america',
        'spain',
        'sudan',
        'syria',
        'thailand',
        'thaïlande',
        'tibet',
        'tunisia',
        'tunisie',
        'turkey',
        'uzbekistan',
        'vietnam',
        'yemen',
        'égypte',
    },
    "signature_traditions": {
        'kente': 'Ghana',
        'adinkra': 'Ghana',
        'akan goldweights': 'Ghana',
        'asante stool': 'Ghana',
        'kuba cloth': 'Democratic Republic of the Congo',
        'raffia velvet': 'Democratic Republic of the Congo',
        'nkisi nkondi': 'Democratic Republic of the Congo',
        'minkisi': 'Democratic Republic of the Congo',
        'byeri': 'Gabon',
        'fang reliquary': 'Gabon',
        'ife bronzes': 'Nigeria',
        'benin bronzes': 'Nigeria',
        'nok terracotta': 'Nigeria',
        'gelede mask': 'Nigeria',
        'ibeji': 'Nigeria',
        'processional cross': 'Ethiopia',
        'ethiopian icon': 'Ethiopia',
        'magdala treasure': 'Ethiopia',
        'shamma': 'Ethiopia',
        'kanga': 'Tanzania',
        'makonde mask': 'Tanzania',
        'shuka': 'Kenya',
        'maasai beadwork': 'Kenya',
        'kikuyu gourd': 'Kenya',
        'himba otjize': 'Namibia',
        'san rock art': 'Botswana',
        'zulu beadwork': 'South Africa',
        'ndebele wall painting': 'South Africa',
        'xhosa pipe': 'South Africa',
        'wolof boubou': 'Senegal',
        'senufo kpelie': '_regional',
    },
}


# Hardcoded region dicts above are the legacy fallback. Prefer the
# seed-driven registry — every seed file may contain a `region_places`
# block with the same three fields (place_to_country, reject_places,
# signature_traditions). Adding a new region is then a pure seed diff.
_LEGACY_REGIONS = {
    "central-asia": CENTRAL_ASIA,
    "central_asia": CENTRAL_ASIA,
    "sub-saharan-africa": SUB_SAHARAN_AFRICA,
    "sub_saharan_africa": SUB_SAHARAN_AFRICA,
    "middle-east-north-africa": MENA,
    "middle_east_north_africa": MENA,
    "southeast-asia": SOUTHEAST_ASIA,
    "southeast_asia": SOUTHEAST_ASIA,
}


def _load_regions_from_seed() -> dict:
    """Scan data/seed/*.json and pull each `region_places` block into a
    keyed-by-region-slug dict. Falls back to the legacy hardcoded dicts if
    a region has no seed entry (backwards-compat during migration)."""
    import json
    from pathlib import Path
    seeds = Path(__file__).resolve().parents[2] / "data" / "seed"
    out: dict = {}
    if not seeds.exists():
        return dict(_LEGACY_REGIONS)
    for p in seeds.glob("*.json"):
        try:
            d = json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            continue
        rp = d.get("region_places")
        if not rp:
            continue
        # Normalize reject_places to a set for O(1) lookup
        rp = {
            "place_to_country": rp.get("place_to_country") or {},
            "reject_places": set(rp.get("reject_places") or []),
            "signature_traditions": rp.get("signature_traditions") or {},
        }
        # Register under both dash and underscore slug variants
        for slug in {p.stem, d.get("region") or p.stem}:
            slug_dash = slug.replace("_", "-")
            slug_us = slug.replace("-", "_")
            out[slug_dash] = rp
            out[slug_us] = rp
    # Fill in any legacy regions that don't have a seed migration yet
    for k, v in _LEGACY_REGIONS.items():
        out.setdefault(k, v)
    return out


REGIONS = _load_regions_from_seed()


def route_place_to_country(region_slug: str, place: str, object_type: str = "") -> str | None:
    """Given a place string and object_type, return the country slug to file
    the record under, or None to reject.

    "_regional" is returned when place is generic ("Central Asia") — caller
    can decide to store in _regional/ or use signature-tradition fallback.
    """
    region = REGIONS.get(region_slug)
    if not region:
        return None
    place_l = (place or "").strip().lower()
    obj_type_l = (object_type or "").strip().lower()

    # Explicit reject
    if place_l in region["reject_places"]:
        return None
    # Some place strings may contain a rejected token as a substring
    # ("Cairo, Egypt")
    for bad in region["reject_places"]:
        if bad in place_l:
            return None

    # Direct place match
    if place_l in region["place_to_country"]:
        return region["place_to_country"][place_l]
    # Substring match (place might be "Bukhara, Uzbekistan")
    for token, country in region["place_to_country"].items():
        if token in place_l:
            return country

    # No place match — try signature tradition fallback
    for sig_token, sig_country in region["signature_traditions"].items():
        if sig_token in obj_type_l:
            return sig_country

    return None
